services:
  camouflage:
    image: nginx:1.23
    restart: always
    network_mode: host

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  ha-proxy:
    image: haproxy:2.3
    restart: always
    network_mode: host

    volumes:
      - ./ha-proxy:/usr/local/etc/haproxy

  marzban-node:
    build: .
    # image: gozargah/marzban-node:latest
    restart: always
    network_mode: host

    # env_file: .env
    environment:
      # SSL_CERT_FILE: "/var/lib/marzban-node/ssl_cert.pem"
      # SSL_KEY_FILE: "/var/lib/marzban-node/ssl_key.pem"
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/ssl_client_cert.pem"
      # SERVICE_PROTOCOL: "rest"

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
